# which benchmarks to run
# benchmarks = '../../benchmarks/**/*.bril'
benchmarks = '../../examples/test/**/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.global_constant_folding]
pipeline = [
  "bril2json",
  "python3 global_constant_folding.py",
  "brili -p {args}",
]
